server:
  applicationConnectors:
    - type: http
      port: 8080
#  rootPath: /api/*
#  applicationContextPath: /
  adminConnectors:
    - type: http
      port: 9003

#database:
#  driverClass: org.h2.Driver
#  user: sa
#  url: jdbc:h2:mem:interviewDB;MODE=PostgreSQL
database:
  driverClass: org.postgresql.Driver
  user: sa
  url: jdbc:postgresql://localhost:54322/interviewDB

queue:
  type: "QUARTZ"
  quartz:
    org.quartz.threadPool.threadCount: "1"
    org.quartz.jobStore.class: org.quartz.impl.jdbcjobstore.JobStoreTX
    org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
    org.quartz.jobStore.dataSource: queue
    org.quartz.jobStore.tablePrefix: "ZZ_QRTZ_"
    org.quartz.jobStore.isClustered: true
    org.quartz.dataSource.queue.connectionProvider.class: franroa.queue.config.QueueConnectionProvider

logging:
  level: INFO
  loggers:
    net.klarna:
      level: DEBUG